// This file was partially generated by the electron-vite package (2023).
// The automatically generated code will be surrounded by EQUAL signs.
// This information was obtained while consulting the Electron documentation on context isolation and security considerations (2023)."
// https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations

/// <reference types="vite-plugin-electron/electron-env" />

export interface IElectronAPI {
  getData: () => Promise<void>;
  close: () => Promise<void>;
}

export interface IAPI {
  chrome: () => string;
  node: () => string;
  electron: () => string;
}

// ========================  GENERATED CODE ========================
declare namespace NodeJS {
  interface ProcessEnv {
    DIST: string
  }
}

interface Window {
  electron: IElectronAPI,
  api: IAPI
}
// ======================= END OF GENERATED CODE ================================