// This file was generated by electron-vite package (2023)

/// <reference types="vite-plugin-electron/electron-env" />

// made whilst looking at https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations
export interface IElectronAPI {
  getData: () => Promise<void>;
}
// -----

declare namespace NodeJS {
  interface ProcessEnv {
    /**
     * The built directory structure
     *
     * ```tree
     * ├─┬─┬ dist
     * │ │ └── index.html
     * │ │
     * │ ├─┬ dist-electron
     * │ │ ├── main.js
     * │ │ └── preload.js
     * │
     * ```
     */
    DIST: string
    /** /dist/ or /public/ */
    VITE_PUBLIC: string
  }
}

// Used in Renderer process, expose in `preload.ts`
interface Window {
  electron: IElectronAPI,
}
