// This file was partially generated by electron-vite package (2023)
// The automatically generated code will be surrounded by EQUAL signs.
// Also made whilst looking at https://www.electronjs.org/docs/latest/tutorial/context-isolation#security-considerations

/// <reference types="vite-plugin-electron/electron-env" />

export interface IElectronAPI {
  getData: () => Promise<void>;
}

export interface IAPI {
  chrome: () => string;
  node: () => string;
  electron: () => string;
}

// ========================  GENERATED CODE ========================
declare namespace NodeJS {
  interface ProcessEnv {
    DIST: string
    VITE_PUBLIC: string
  }
}

interface Window {
  electron: IElectronAPI,
  api: IAPI
}
// ======================= END OF GENERATED CODE ================================